#!/bin/sh


local chpwd chpwd_functions


virtualenv_sh_verify_workon_home || return 1

eval "env_name=\$$#"

# If the last argument is an option, assume we're not actually making a
# virtualenv.
if [ ${env_name#-} != ${env_name} ]; then
    env_name=
fi


if [ ${env_name} ]; then
    virtualenv_sh_run_hook "premkvirtualenv" "$env_name"
fi

( cd ${WORKON_HOME}
  virtualenv "$@" 
) || return 1

if [ ${env_name} ]; then
    virtualenv_sh_run_hook "postmkvirtualenv" "$env_name"

    workon ${env_name}
fi
