#!/bin/sh


local chpwd chpwd_functions


virtualenv-sh-verify-workon-home || return 1

eval "env_name=\$$#"

# If the last argument is an option, assume we're not actually making a
# virtualenv.
if [ ${env_name#-} != ${env_name} ]; then
    unset env_name
fi


if [ ${env_name} ]; then
    virtualenv-sh-run-hook "premkvirtualenv" "$env_name"
fi

( cd ${WORKON_HOME}
  virtualenv "$@" 
) || return 1

if [ ${env_name} ]; then
    workon ${env_name}

    virtualenv-sh-run-hook "postmkvirtualenv"
fi
