#!/bin/sh

virtualenv_sh_verify_workon_home || return 1


if [ -z "${1:-}" ]; then
    echo "Please specify an enviroment." >&2
    return 1
else
    _rmvirtualenv_env_name="$1"
fi

_rmvirtualenv_env_dir="${WORKON_HOME}/${_rmvirtualenv_env_name}"

if [ "${VIRTUAL_ENV}" = "$_rmvirtualenv_env_dir" ] && ! deactivate; then
    echo "ERROR: unable to deactivate ${_rmvirtualenv_env_name}"
    return 1
fi

virtualenv_sh_run_hook "prermvirtualenv" "${_rmvirtualenv_env_name}"

rm -rf "${_rmvirtualenv_env_dir}"

virtualenv_sh_run_hook "postrmvirtualenv" "${_rmvirtualenv_env_name}"


unset _rmvirtualenv_env_name
unset _rmvirtualenv_env_dir
