#!/bin/sh

virtualenv_sh_verify_workon_home || return 1


if [ -z "${1:-}" ]; then
    echo "Please specify an enviroment." >&2
    return 1
else
    env_name=$1
fi

env_dir="$WORKON_HOME/$env_name"

if [ "$VIRTUAL_ENV" = "$env_dir" ] && ! deactivate; then
    echo "ERROR: unable to deactivate ${env_name}"
    return 1
fi

virtualenv_sh_run_hook "prermvirtualenv" "$env_name"

rm -rf "$env_dir"

virtualenv_sh_run_hook "postrmvirtualenv" "$env_name"
