#!/bin/sh

# $1 is the hook name
# $2 is the env name

_run_local_hook_env_path="${WORKON_HOME}/$2"

if [ -n "$_run_local_hook_env_path" ] && [ -r "$_run_local_hook_env_path/bin/$1" ]; then
    . "$_run_local_hook_env_path/bin/$1"
fi


unset _run_local_hook_env_path
