#!/bin/zsh


function _virtualenv-sh-complete-virtualenvs () {
    reply=($(virtualenv-sh-virtualenvs))
}

function _virtualenv-sh-complete-cdvirtualenv () {
    reply=( $(cdvirtualenv && ls -d ${1}*) )
}

function _virtualenv-sh-complete-sitepackages () {
    reply=( $(cdsitepackages && ls -d ${1}*) )
}


compctl -K _virtualenv-sh-complete-virtualenvs workon rmvirtualenv
compctl -K _virtualenv-sh-complete-cdvirtualenv cdvirtualenv
compctl -K _virtualenv-sh-complete-sitepackages cdsitepackages
